name: CI
on: [push, pull_request]

jobs:
  haxelib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/upload-artifact@v6
        with:
          name: moonshine-feathersui-text-editor-haxelib
          path: |
            src/
            haxelib.json
            README.md
            LICENSE
          if-no-files-found: error

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime 7.8.0 --quiet
          haxelib install openfl 8.9.7 --quiet
          haxelib install actuate --quiet
          haxelib install markdown-openfl-textfield --quiet
          haxelib install feathersui --quiet
          haxelib git moonshine-openfl-language-client https://github.com/Moonshine-IDE/moonshine-openfl-language-client.git --quiet
          haxelib install dox --quiet
          haxelib dev moonshine-feathersui-text-editor $GITHUB_WORKSPACE
      - name: Build API reference
        working-directory: docs
        run: haxe docs.hxml
      - uses: actions/upload-artifact@v6
        with:
          name: moonshine-feathersui-text-editor-api-reference
          path: bin/api/
          if-no-files-found: error
      - name: Upload Site
        if: ${{ github.repository_owner == 'Moonshine-IDE' && github.event_name != 'pull_request' && github.ref_name == 'master' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: bin/api/

  flash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime 7.8.0 --quiet
          haxelib install openfl 8.9.7 --quiet
          haxelib install actuate --quiet
          haxelib install markdown-openfl-textfield --quiet
          haxelib install feathersui --quiet
          haxelib git moonshine-openfl-language-client https://github.com/Moonshine-IDE/moonshine-openfl-language-client.git --quiet
          haxelib dev moonshine-feathersui-text-editor $GITHUB_WORKSPACE
      - name: Build Flash .swc library
        run: haxelib run openfl build flash -debug
      - uses: actions/upload-artifact@v6
        with:
          name: moonshine-feathersui-text-editor-flash
          path: |
            bin/flash/bin/*.swc
            src/
            README.md
            LICENSE
          if-no-files-found: error
